export const gamingWords = [
	{ word: 'Hawes', hint: '' },
	{ word: 'Steve', hint: '' },
	{ word: 'Mario', hint: 'Iconic plumber from Nintendo' },
	{ word: 'Mario', hint: 'Iconic plumber from Nintendo' },
	{ word: 'Sonic', hint: 'Fast blue hedgehog from Sega' },
	{ word: 'Zelda', hint: 'Princess from a popular Nintendo series' },
	{ word: 'Tetra', hint: 'Pirate character from Zelda series' },
	{ word: 'Luigi', hint: "Mario's brother" },
	{ word: 'Crash', hint: 'Bandicoot character from PlayStation' },
	{ word: 'Knack', hint: 'Game title from PlayStation' },
	{ word: 'Samus', hint: 'Bounty hunter from Metroid series' },
	{ word: 'Ninja', hint: 'Popular streamer and character type' },
	{ word: 'Peach', hint: 'Princess from Mario series' },
	{ word: 'Kirby', hint: 'Pink puffball from Nintendo' },
	{ word: 'Cloud', hint: 'Main character from Final Fantasy VII' },
	{ word: 'Snake', hint: 'Protagonist of Metal Gear series' },
	{ word: 'Akuma', hint: 'Character from Street Fighter' },
	{ word: 'Cammy', hint: 'Character from Street Fighter' },
	// { word: "Ness", hint: "Protagonist from EarthBound" },
	{ word: 'Falco', hint: 'Pilot from Star Fox series' },
	{ word: 'Marth', hint: 'Character from Fire Emblem series' },
	{ word: 'Lucia', hint: 'Character from Fire Emblem series' },
	{ word: 'Mappy', hint: 'Mouse police character from Namco' },
	{ word: 'Ganon', hint: 'Main antagonist in the Zelda series' },
	{ word: 'Gordo', hint: 'Enemy from Kirby series' },
	{ word: 'Genji', hint: 'Character from Overwatch' },
	{ word: 'Talon', hint: 'Assassin character from League of Legends' },
	{ word: 'Lucio', hint: 'Support character from Overwatch' },
	{ word: 'Blaze', hint: 'Character from Streets of Rage' },
	{ word: 'Celes', hint: 'Character from Final Fantasy VI' },
	{ word: 'Banjo', hint: 'Bear from Banjo-Kazooie' },
	{ word: 'Sagat', hint: 'Character from Street Fighter' },
	// { word: "Jinx", hint: "Character from League of Legends" },
	// { word: "Ashe", hint: "Character from League of Legends" },
	{ word: 'Luxio', hint: 'Pokémon from Generation IV' },
	// { word: "Sona", hint: "Character from League of Legends" },
	// { word: "Fizz", hint: "Character from League of Legends" },
	{ word: 'Jaxar', hint: 'Character from League of Legends' },
	// { word: "Pyke", hint: "Character from League of Legends" },
	// { word: "Rook", hint: "Piece in chess, also a character name" },
	{ word: 'Shade', hint: 'Character from various games' },
	{ word: 'Riven', hint: 'Character from League of Legends' },
	{ word: 'Urgot', hint: 'Character from League of Legends' },
	{ word: 'Vayne', hint: 'Character from League of Legends' },
	{ word: 'Braum', hint: 'Character from League of Legends' },
	// { word: "Nami", hint: "Character from League of Legends" },
	{ word: 'Renek', hint: 'Character from League of Legends' },
	{ word: 'Sylas', hint: 'Character from League of Legends' },
	{ word: 'Kayle', hint: 'Character from League of Legends' },
	{ word: 'Shaco', hint: 'Character from League of Legends' },
	{ word: 'Karma', hint: 'Character from League of Legends' },
	{ word: 'Ember', hint: 'Character or item from various games' },
	{ word: 'Trist', hint: 'Character from League of Legends' },
	{ word: 'Patch', hint: 'Game update' },
	// { word: "Irelia", hint: "Character from League of Legends" },
	{ word: 'Volib', hint: 'Character from League of Legends' },
	{ word: 'Whisp', hint: 'Character or item from various games' },
	{ word: 'Velma', hint: 'Character from Scooby-Doo, appears in games' },
	{ word: 'Rydia', hint: 'Character from Final Fantasy IV' },
	{ word: 'Poppy', hint: 'Character from League of Legends' },
	{ word: 'Raven', hint: 'Character from various games' },
	{ word: 'Midna', hint: 'Character from Zelda series' },
	{ word: 'Rikku', hint: 'Character from Final Fantasy X' },
	{ word: 'Orisa', hint: 'Character from Overwatch' },
	{ word: 'Tails', hint: 'Character from Sonic the Hedgehog' },
	{ word: 'Tidus', hint: 'Character from Final Fantasy X' },
	{ word: 'Moses', hint: 'Character or reference from various games' },
	{ word: 'Doomg', hint: 'Character from Doom series' },
	{ word: 'Khezu', hint: 'Monster from Monster Hunter series' },
	{ word: 'Monok', hint: 'Character from Danganronpa' },
	{ word: 'Raich', hint: 'Pokémon character, short for Raichu' },
]
