const items = [
	{
		title: 'Twitter',
		href: 'https://twitter.com/BlueHarvestPod',
		icon: 'fa-brands fa-twitter',
		subtitle: '',
		background: '#1da1f2',
	},
	{
		title: 'Patreon',
		href: 'https://www.patreon.com/blueharvestpodcast',
		icon: 'fa-brands fa-patreon',
		subtitle: '',
		background: 'var(--patreon)',
	},
	{
		title: 'Apple Podcasts',
		href: 'https://podcasts.apple.com/us/podcast/blue-harvest-a-star-wars-podcast/id1009917662?itsct=podcast_box&itscg=30200&ls=1',
		icon: 'fa-solid fa-podcast',
		subtitle: '',
		background: 'var(--applePodcasts)',
	},
	{
		title: 'Spotify',
		href: 'https://open.spotify.com/show/3Krn2ePCbILvzORISjh2PT',
		icon: 'fa-brands fa-spotify',
		subtitle: '',
		background: '#1db954',
	},
	{
		title: 'Twitch',
		href: 'http://www.twitch.tv/blueharvestpod',
		icon: 'fa-brands fa-twitch',
		subtitle: '',
		background: '#9146ff',
	},
	{
		title: 'Instagram',
		href: 'https://www.instagram.com/blueharvestpod',
		icon: 'fa-brands fa-instagram',
		subtitle: '',
		background: '#c13584',
	},
	{
		title: 'Voicemails & Emails',
		href: 'mailto:blueharvestpodcast@gmail.com',
		icon: 'fa-solid fa-mailbox',
		subtitle: '',
		background: '#52565e',
	},
	{
		title: 'Threads',
		href: 'https://www.threads.net/@blueharvestpod',
		icon: 'fak fa-threads',
		subtitle: '',
		background: '#000',
	},
	{
		title: 'Overcast',
		// overcast://x-callback-url/add?url=https%3A%2F%2Ffeed.podbean.com%2Fblueharvestpodcast%2Ffeed.xml
		href: 'https://overcast.fm/itunes1009917662',
		icon: 'fak fa-overcast fa-lg',
		subtitle: '',
		background: '#fc7e0f',
	},
	{
		title: 'Merch Store',
		href: 'https://www.teepublic.com/user/blueharvestpodcast',
		icon: 'fa-solid fa-shirt',
		// subtitle: 'Moisture farmer swag',
		background: '#19b1ff',
	},
	{
		title: 'Discord',
		href: 'https://discord.gg/CZFSuSpmD8',
		icon: 'fa-brands fa-discord',
		subtitle: '',
		background: '#5865F2',
	},
	{
		title: 'Google Play',
		href: 'https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkLnBvZGJlYW4uY29tL2JsdWVoYXJ2ZXN0cG9kY2FzdC9mZWVkLnhtbA',
		icon: 'fa-brands fa-google-play',
		subtitle: '',
		background: '#4285f4',
	},
	// {
	// 	title: 'Stitcher',
	// 	href: 'https://www.stitcher.com/show/blue-harvest-a-star-wars-podcast',
	// 	icon: 'fa-solid fa-waveform',
	// 	subtitle: '',
	// 	background: '#ec8900',
	// },
	{
		title: 'PodBean',
		href: 'https://blueharvestpodcast.podbean.com/',
		icon: 'fa-solid fa-coffee-beans',
		subtitle: '',
		background: '#8fc31f',
	},
	{
		title: 'YouTube',
		href: 'https://www.youtube.com/BlueHarvestAStarWarsPodcast',
		icon: 'fa-brands fa-youtube',
		subtitle: '',
		background: '#ff0000',
	},
	{
		title: 'RSS',
		href: 'https://feed.podbean.com/blueharvestpodcast/feed.xml',
		icon: 'fa-solid fa-rss',
		subtitle: '',
		background: '#0000ff',
	},
	{
		title: 'Stoned Cobra',
		href: 'https://stonedcobra.bandcamp.com/',
		icon: 'fa-solid fa-snake',
		subtitle: '',
		background: '#3CC70F',
	},
	{
		title: 'Goodpods',
		href: 'https://goodpods.com/podcasts/blue-harvest-a-star-wars-podcast-84967',
		icon: 'fak fa-goodpods',
		subtitle: '',
		background: '#fcdb00',
		color: 'var(--bg)',
	},
	{
		title: 'Hive Social',
		href: 'https://www.hivesocial.app/',
		icon: 'fak fa-hive-social',
		subtitle: '@blueharvest',
		background: '#d34eff',
	},
	{
		title: 'OnlyFans',
		icon: 'fak fa-onlyfans',
		background: '#008ccf',
		alert: () => {
			alert(`This doesn't exist (yet) but we're watching you... ಠ_ಠ`)
		},
	},
]

export default items
